// Metro resolves require() statically, so every sprite is listed by hand. Relic
// art is the hi-bit 32px port, bosses and the curse tile are the 16px set.
export const RELIC_SPRITES = {
  anchor: require('../../assets/sprites/relics/anchor.png'),
  appraiser: require('../../assets/sprites/relics/appraiser.png'),
  aria: require('../../assets/sprites/relics/aria.png'),
  ascetic: require('../../assets/sprites/relics/ascetic.png'),
  ballast: require('../../assets/sprites/relics/ballast.png'),
  bookend: require('../../assets/sprites/relics/bookend.png'),
  cadence: require('../../assets/sprites/relics/cadence.png'),
  cascade: require('../../assets/sprites/relics/cascade.png'),
  chorus: require('../../assets/sprites/relics/chorus.png'),
  collector: require('../../assets/sprites/relics/collector.png'),
  consonance: require('../../assets/sprites/relics/consonance.png'),
  coupon: require('../../assets/sprites/relics/coupon.png'),
  crucible: require('../../assets/sprites/relics/crucible.png'),
  diphthong: require('../../assets/sprites/relics/diphthong.png'),
  foundation: require('../../assets/sprites/relics/foundation.png'),
  gambit: require('../../assets/sprites/relics/gambit.png'),
  glasscannon: require('../../assets/sprites/relics/glasscannon.png'),
  goldrush: require('../../assets/sprites/relics/goldrush.png'),
  haggler: require('../../assets/sprites/relics/haggler.png'),
  hermit: require('../../assets/sprites/relics/hermit.png'),
  highroller: require('../../assets/sprites/relics/highroller.png'),
  hoard: require('../../assets/sprites/relics/hoard.png'),
  jeweler: require('../../assets/sprites/relics/jeweler.png'),
  keystone: require('../../assets/sprites/relics/keystone.png'),
  lexicographer: require('../../assets/sprites/relics/lexicographer.png'),
  longhand: require('../../assets/sprites/relics/longhand.png'),
  marathoner: require('../../assets/sprites/relics/marathoner.png'),
  merchant: require('../../assets/sprites/relics/merchant.png'),
  mirror: require('../../assets/sprites/relics/mirror.png'),
  miser: require('../../assets/sprites/relics/miser.png'),
  momentum: require('../../assets/sprites/relics/momentum.png'),
  novella: require('../../assets/sprites/relics/novella.png'),
  numismatist: require('../../assets/sprites/relics/numismatist.png'),
  philosopher: require('../../assets/sprites/relics/philosopher.png'),
  polysyllable: require('../../assets/sprites/relics/polysyllable.png'),
  prism: require('../../assets/sprites/relics/prism.png'),
  prospector: require('../../assets/sprites/relics/prospector.png'),
  smelter: require('../../assets/sprites/relics/smelter.png'),
  sonorant: require('../../assets/sprites/relics/sonorant.png'),
  speculator: require('../../assets/sprites/relics/speculator.png'),
  staccato: require('../../assets/sprites/relics/staccato.png'),
  symmetry: require('../../assets/sprites/relics/symmetry.png'),
  tally: require('../../assets/sprites/relics/tally.png'),
  taxman: require('../../assets/sprites/relics/taxman.png'),
  temperance: require('../../assets/sprites/relics/temperance.png'),
  tycoon: require('../../assets/sprites/relics/tycoon.png'),
  vein: require('../../assets/sprites/relics/vein.png'),
  vowelMult: require('../../assets/sprites/relics/vowelMult.png'),
  whetstone: require('../../assets/sprites/relics/whetstone.png'),
};

export const BOSS_SPRITES = {
  minLength: require('../../assets/sprites/boss/minLength.png'),
  noRepeatLong: require('../../assets/sprites/boss/noRepeatLong.png'),
  maxOneVowel: require('../../assets/sprites/boss/maxOneVowel.png'),
  vowelBlight: require('../../assets/sprites/boss/vowelBlight.png'),
  flint: require('../../assets/sprites/boss/flint.png'),
  noRepeatShape: require('../../assets/sprites/boss/noRepeatShape.png'),
};

export const CURSE_SPRITE = require('../../assets/sprites/curse.png');
